from pymongo import AsyncMongoClient
from app.core.config import DATABASE_URL, DATABASE_NAME

client = AsyncMongoClient(DATABASE_URL)
db = client[DATABASE_NAME]
users_collection = db["users"]
roles_collection = db["roles"]
permissions_collection = db["permissions"]
tasks_collection = db["tasks"]
projects_collection = db["projects"]
clients_collection = db["clients"]
attendance_collection = db["attendance"]
employees_collection = db["employees"]
checklist_templates_collection = db["checklist_templates"]
system_configurations_collection = db["system_configurations"]
holidays_collection = db["holidays"]
nda_requests_collection = db["nda_requests"]
payslips_collection = db["payslips"]
employee_documents_collection = db["employee_documents"]
documents_collection = db["documents"]
document_categories_collection = db["document_categories"]
chat_sessions_collection = db["chat_sessions"]
chat_messages_collection = db["chat_messages"]
shifts_collection = db["shifts"]
assets_collection = db["assets"]
asset_categories_collection = db["asset_categories"]
blogs_collection = db["blogs"]
departments_collection = db["departments"]
expense_categories_collection = db["expense_categories"]
expenses_collection = db["expenses"]
payslip_components_collection = db["payslip_components"]
leave_types_collection = db["leave_types"]
feedbacks_collection = db["feedback"]
leave_requests_collection = db["leave_requests"]
pending_biometric_logs_collection = db["pending_biometric_logs"]
milestones_roadmaps_collection = db["milestones_roadmaps"]
